### ISSUE TITLE
[Bug]: Android MapView onMapIdle isGestureActive is always false

### ISSUE THREAD

**Issue by PentamapFlorian** [rnmapbox/maps#2817]
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.2

### Standalone component to reproduce

```jsx
import React from 'react';
import Mapbox from '@rnmapbox/maps';

const Map = () => {
  const onMapIdle = (region) => {
    console.log('onMapIdle. region =', region);
  };

  const onCameraChanged = (region) => {
    console.log('onCameraChanged. region =', region);
  };

  return (
    <Mapbox.MapView
      style={{ flex: 1 }}
      onMapIdle={onMapIdle}
      onCameraChanged={onCameraChanged}
    />
  );
};
export default Map;
```

### Observed behavior and steps to reproduce

If I move the map by any gesture onMapIdle always returns isGestureActive: false:
'onMapIdle. region =', { gestures: { isGestureActive: false },...'

However onCamera Changed returns isGestureActive: true
'onCameraChanged. region =', { gestures: { isGestureActive: true },...'

### Expected behavior

onMapIdle should also return isGestureActive: true if any Gesture has been performed

**Comment by PentamapFlorian** [comment]
It works as expected on iOS devices

**Comment by devoren** [comment]
same issue

**Comment by mfazekas** [comment]
> @PentamapFlorian check this [#1888 (comment)](https://github.com/rnmapbox/maps/issues/1888#issuecomment-1126943173)
> 
> > **onMapIdle experimental and implemented only on iOS**

It has changed since then. Now `onMapIdle` is the recommended now and the `onRegionDidChange` is now deprecated.

**Comment by devoren** [comment]
@mfazekas Then I have the same bug

**Comment by josescgar** [comment]
We are experiencing the same issue. iOS works as expected but it is always `false` in Android.

**Comment by somasekharkakarla** [comment]
@mfazekas isGestureActive on MapChange still has an issue. It is false only in some times like 5%. It is always true even if i released the finger from the map. Please test it once again. i used v10.0.5 and also tested in v10.0.6

**Comment by devoren** [comment]
@somasekharkakarla i can confirm the problem still exists

**Comment by thomasgrivet** [comment]
Hello, this issue is still present on Android. isGestureActive is always false.

**Comment by mfazekas** [comment]
https://github.com/rnmapbox/maps/issues/2817#issuecomment-1551210720
>  It is false only in some times like 5%. It is always true even if i released the finger from the map.

https://github.com/rnmapbox/maps/issues/2817#issuecomment-1554442285
> . isGestureActive is always false.

Which one is the case?

**Comment by nixolas1** [comment]
`onCameraChanged={changedView}` works fine here. Triggers very often, so maybe not perfect for all usecases, but with a event-debouncer it's fine.

```
  const changedView = ({properties, gestures}) => { 
      if (gestures?.isGestureActive) setHasMovedMap(true)
   }
  
```

**Comment by mfazekas** [comment]
@RyanTG isGestureACtive should be mostly false with `onMapIdle` per my understanding, as if gesture is active then the map will not be idle but changing. `onChameraChanged` should be coalesced with 1.0.8+ so if you take a long time processing one event next ones will be merged, but you can also debounce - which is 3 lines or so.

**Comment by RyanTG** [comment]
Ah I see - that seems to make sense. But it's confusing to me because `gestures?.isGestureActive` is always `true` in iOS with `onMapIdle` if the user has moved the map (so, Android and iOS seem inconsistent with each other). 

Basically, what I'm trying to register is "Did the user just pan or zoom the map and have they now stopped?"
