### ISSUE TITLE
[Bug]: Map doesn't entirely correspond to the style URL

### ISSUE THREAD

**Issue by ABertaud** [rnmapbox/maps#3820]
### Mapbox Implementation

Mapbox

### Mapbox Version

11.8.0

### React Native Version

0.76.7

### Platform

iOS

### `@rnmapbox/maps` version

10.1.33

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera bounds={{"ne": [139.778, 35.685201], "paddingBottom": 500, "paddingLeft": 60, "paddingRight": 60, "paddingTop": 300, "sw": [135.48112, 34.676707695652176]}} zoomLevel={12} />
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

It's been almost 2 months I had released my app with a styled URL map without issue.

The 31th of March, my map suddenly stopped corresponding to the styled URL.

You can see the difference between to two images below, color saturation remains good, but the roads seems to be grey instead of white. 

rnmapbox Map:
![Image](https://github.com/user-attachments/assets/cdaa6712-177f-4fc5-ab72-b291b3bd76ca)

Styled Map URL:
![Image](https://github.com/user-attachments/assets/cec5ac7d-89e5-46d5-8cb6-7ab989b2104a)

[Preview URL of the styled map](https://api.mapbox.com/styles/v1/abertaud/cm3elvh0t005801pg4mqr50ob.html?title=view&access_token=pk.eyJ1IjoiYWJlcnRhdWQiLCJhIjoiY20zY3RxNnV4MjBubTJ2c2NqbHBwdDZpZSJ9.Q8DAm9AC363E54vA5QhGgQ&zoomwheel=true&fresh=true#8.8/35.608/139.7757)

### Expected behavior

The expected behavior is that rnmapbox's map should match the style from the url.

**Comment by ABertaud** [comment]
@mathieupost
maybe related to #3822?

**Comment by RyanTG** [comment]
Are you thinking it's fixed by that commit or caused by that? Looks like you created this issue before that commit was merged - so, is your issue fixed in 10.1.38?

Also, `The 31th of March, my map suddenly stopped corresponding to the styled URL.` to me that doesn't point to an rnmapbox issue, since you didn't update anything at that time. Did you try other custom styles to see if those are displaying correctly?

**Comment by ABertaud** [comment]
Thanks for your reply!

Sadly it didn't fix. I also tried with different styles, but the issue is still remaining. It seems related to rnmapbox since my map is perfectly working on web.

If i can be more accurate, `Trunk roads, Other roads, Motorway roads` styles (color) don't seem to apply anymore with rnmapbox.

In Mapbox Studio:
![Image](https://github.com/user-attachments/assets/50f262a7-8fbc-4caa-aa1e-98b8ca68922d)

**Comment by mathieupost** [comment]
> [@mathieupost](https://github.com/mathieupost) maybe related to [#3822](https://github.com/rnmapbox/maps/pull/3822)?

I don't think it is related unfortunately. My fix was specifically for `<StyleImport>` usage which has nothing to do with styled url as far as I know.

**Comment by ABertaud** [comment]
Well, this has been fixed recently (2 weeks ago), I didn't have to bump the rnmapbox package.

The issue seems to come from mapbox directly.
